task:
  name: "Infinity_X_2.9_Manual_Build_Joe"
  # السطر اللي جاي ده هو "الزرار" اللي هيخليك تشغله بنفسك
  trigger_type: manual 
  timeout_in: 120m
  gce_instance:
    image_project: ubuntu-os-cloud
    image_family: ubuntu-2204-lts
    cpu: 8
    memory: 32G
    disk: 250 

  # 1. تثبيت الترسانة (الأدوات)
  setup_script:
    - sudo apt-get update
    - sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig ccache bc libssl-dev rsync python3 python3-pip ninja-build python-is-python3 libxml2 aria2 git-lfs openjdk-17-jdk imagemagick libelf-dev libncursesw5-dev libghc-zlib-dev gcc-multilib g++-multilib lz4 liblz4-tool pigz openssh-client screen
    - mkdir -p ~/bin
    - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod a+x ~/bin/repo
    - export PATH="$HOME/bin:$PATH"

  # 2. تحميل السورس والـ Trees (T505N)
  sync_script:
    - export PATH="$HOME/bin:$PATH"
    - mkdir -p ~/android && cd ~/android
    - git config --global user.email "joe@alexandria.com"
    - git config --global user.name "Joe"
    - repo init -u https://github.com/ProjectInfinity-X/manifest -b 15 --depth=1
    - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
    
    # تحميل الـ Trees (Android 15)
    - git clone --depth=1 https://github.com/LineageOS/android_device_samsung_gta4l -b lineage-22.1 device/samsung/gta4l
    - git clone --depth=1 https://github.com/LineageOS/android_device_samsung_gta4l-common -b lineage-22.1 device/samsung/gta4l-common
    - git clone --depth=1 https://github.com/LineageOS/android_kernel_samsung_gta4l -b lineage-22.1 kernel/samsung/gta4l
    - git clone --depth=1 https://github.com/TheMuppets/proprietary_vendor_samsung_gta4l -b lineage-22.1 vendor/samsung/gta4l
    - git clone --depth=1 https://github.com/TheMuppets/proprietary_vendor_samsung_gta4l-common -b lineage-22.1 vendor/samsung/gta4l-common
    - git clone --depth=1 https://github.com/LineageOS/android_hardware_samsung -b lineage-22.1 hardware/samsung

  # 3. معركة البناء
  build_script:
    - export PATH="$HOME/bin:$PATH"
    - cd ~/android
    - source build/envsetup.sh
    - lunch infinity_gta4l-userdebug || lunch lineage_gta4l-userdebug
    - export USE_CCACHE=1
    - ccache -M 50G
    - mka infinity -j$(nproc --all)

  # 4. الرفع الصاروخي
  upload_script:
    - cd ~/android/out/target/product/gta4l/
    - ROM_FILE=$(ls Infinity-X*.zip | head -n 1)
    - echo "الروم خلصت يا جو.. بنرفعها دلوقتي.."
    - curl https://bashupload.com/ -T "$ROM_FILE" > ~/bash_link.txt
    - echo "---------------------------------------"
    - echo "الرابط أهو يا أسطى جيمي:"
    - cat ~/bash_link.txt
    - echo "---------------------------------------"

  artifacts:
    path: "android/out/target/product/gta4l/Infinity-X*.zip"
